---

- name: Assert control variables
  assert:
    that:
    - nx_hostname is defined
    - nx_hostname|string|length > 0
    - nx_hostname|string != 'SetMe'

- name: Create namespace ({{ nx_namespace }})
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Create DockerHub image pull secret
  k8s:
    definition: "{{ lookup('template', 'secret-dh-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_namespace: "{{ nx_namespace }}"
    pull_secret: "{{ nx_dockerhub_pullsecret }}"
  when: nx_dockerhub_pullsecret|string|length > 0

- name: Creating namespace material
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - serviceaccount
  - role

- name: Relax {{ nx_namespace }} 'default' service account (for cert-manager)
  k8s:
    definition: "{{ lookup('template', 'rolebinding-default-sa.yaml.j2') }}"
    wait: yes

- name: Deploy nginx ({{ nx_hostname }})
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - configmap
  - deployment
  - service
  - ingress
