---
name: lint

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync
    - name: Lint
      run: |
        uv run yamllint .
        find . -type f -name '*.yaml.j2' -exec uv run yamllint {} +
